language: C
dist: trusty
sudo: required

install:
  - pip install --user cpp-coveralls
  - pip3 install meson
  - mkdir build
  - export PATH="`pwd`/build:${PATH}"
  - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build

script:
  - meson build
  - ninja -C build test
  - cppcheck --error-exitcode=42 .
  - echo '#!/usr/bin/env bash' > scanbuild.sh
  - echo 'scan-build --status-bugs "$@"' >> scanbuild.sh
  - chmod +x scanbuild.sh
  - sudo cp scanbuild.sh /usr/bin/
  - SCANBUILD='scanbuild.sh' ninja scan-build -C build

after_success:
  - if [ "$CODECOV_RUN" == 1 ]; then coveralls --build-root build --gcov-options '\-lp'; fi

matrix:
  include:
    - os: linux
      compiler: gcc
      
    - os: linux
      compiler: clang
    
    - os: linux
      compiler: gcc
      env:
        CODECOV_RUN=1
        CFLAGS="-g -O0 -fprofile-arcs -ftest-coverage"

addons:
  apt:
    packages:
      - libcairo2-dev
      - libreadline-dev
      - python3
      - python3-pip
      - cppcheck

