language: C
dist: trusty
sudo: required

install:
  - ./scripts/install_lua53.sh
  - sudo pip3 install meson

script:
  - meson build
  - ninja -C build

addons:
  apt:
    packages:
      - libcairo2-dev
      - libreadline-dev
      - python3
      - python3-pip
      - ninja-build
