# You should copy this to one of:
#
#   $XDG_CONFIG_HOME/mace/config.toml
#   $HOME/.config/mace/config.toml
#   $HOME/.mace.toml
#   /etc/mace.toml
#

[mace]
mainbar   = "quit newcol"
colbar    = "scratch open delcol"
actionbar = "save del undo redo"

font = "LiberationMono-12"

tabwidth = 2

[scroll]

# Assign buttons to scroll actions:
#  up
#  immediate
#  down

"Button-1" = "up"
"Button-2" = "immediate"
"Button-3" = "down"

[keybindings]

# Bind special keys to do what one expects.

"Tab" = "tab"
"S-Tab" = "shifttab"
"Return" = "return"
"S-Return" = "return"
"Delete" = "delete"
"S-Delete" = "delete"
"BackSpace" = "backspace"
"S-BackSpace" = "backspace"
"Left" = "left"
"Right" = "right"
"Up" = "up"
"Down" = "down"

"C-z" = "undo"
"C-y" = "redo"

"C-x" = "cut"
"C-c" = "copy"
"C-v" = "paste"

"C-s" = "save"
"C-w" = "del"

