# You should copy this to one of:
#
#   $XDG_CONFIG_HOME/mace/config.toml
#   $HOME/.config/mace/config.toml
#   $HOME/.mace.toml
#   /etc/mace.toml
#

[mace]
actionbar = "save close undo redo"

# If no files are given open either an empty tab
# or a tab containing a tutorial.
defaulttab = "empty" # tutorial, empty

font = "LiberationMono-12"

tabwidth = 2

[scroll]

# scroll bar should be on the left or right side.
side = "right"

# Assign buttons to scroll actions:
#  up
#  immediate
#  down

"Button-1" = "up"
"Button-2" = "immediate"
"Button-3" = "down"

[keybindings]

# Bind special keys to do what one expects.

"Tab" = "tab"
"Return" = "return"
"S-Return" = "return"
"Delete" = "del"
"S-Delete" = "del"
"BackSpace" = "back"
"S-BackSpace" = "back"
"Left" = "left"
"Right" = "right"
"Up" = "up"
"Down" = "down"

"C-z" = "undo"
"C-y" = "redo"

"C-x" = "cut"
"C-c" = "copy"
"C-v" = "paste"

"C-s" = "save"
"C-w" = "close"

